name: SmartScope
description: "An APP for SmartScope."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
    

  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  device_info_plus: ^9.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
